export enum GEEvents {
    
    START = 'START',
    PAUSE = 'PAUSE',
    ADD_COMPONENT = 'ADD_COMPONENT',
    REMOVE_COMPONENT =  'REMOVE_COMPONENT',
    ADD_GAMEOBJECT = 'ADD_GAMEOBJECT',
    REMOVE_GAMEOBJECT = 'REMOVE_GAMEOBJECT',
}
