export enum GEEvents {
    
    START = 'START',
    PAUSE = 'PAUSE',
    ADD_COMPONENT = 'ADD_COMPONENT',
    REMOVE_COMPONENT =  'REMOVE_COMPONENT',
    INSTANCE_COMPONENT_LOADER = 'INSTANCE_COMPONENT_LOADER',

}